# frozen_string_literal: true

source "https://rubygems.org"

gem 'uni_rails', path: '/usr/local/bundle'
gem "sqlite3"
gem "puma"

# Test
gem "capybara", "~> 3.40"
gem "selenium-webdriver", "~> 4.19"
gem "minitest"
gem "debug"
